version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ap_registration_db
    environment:
      POSTGRES_USER: apuser
      POSTGRES_PASSWORD: Amberson7100!
      POSTGRES_DB: ap_registration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apuser -d ap_registration"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local